tracker_label = 'D3S';

tracker_command = generate_python_command('vot_wrapper', ...
    {'/home/alan/workspace/D3S-git', ...
    '/home/alan/workspace/D3S-git/pytracking', ...
    '/home/alan/workspace/vot/trax/support/python'});

tracker_interpreter = 'python';

tracker_linkpath = {'/home/alan/workspace/vot/trax/build/inst/bin', ...
    '/home/alan/workspace/vot/trax/build/inst/lib'};
